@startuml pr1
left to right direction
actor/ Пользователь as p

rectangle Банкомат {

p --> (авторизация)
(авторизация) -up- (выбор команды)
(выбор команды) -right-> (снять наличные со счёта)
(выбор команды) -right-> (печать справки)
(выбор команды) -right-> (положить наличные на счёт)
(выбор команды) -right-> (выход)

(снять наличные со счёта) --> p: снять
(положить наличные на счёт) --> p: положить

(выбор команды) <-- (снять наличные со счёта)
(выбор команды) <-- (печать справки)
(выбор команды) <-- (положить наличные на счёт)

(выход) --> p

}
@enduml