@startuml pr1_class
class "Пользователь"{
    {field} карта
    {field} pin-код
    {method} + печать справки
    {method} + снять деньги
    {method} + положить деньги
}
class "Авторизация"{
    {field} pin-код пользователя
    {method} - Проверка корректности pin-кода
}
class "Выбор команды"{
    {field} команда
    {method} # снять деньги
    {method} # положить деньги
    {method} # печать справки
}
class "Обработчик"{
    {field} команда
    {method} - обработка команды
}

"Пользователь" --> "Авторизация"
"Авторизация" *-- "Выбор команды"
"Выбор команды" .. "Обработчик"
@enduml