@startuml posled
participant Client as c
participant Server as s
==Установка соединения==
c --> s: Запрос соединения
s --> c: Подготовка соединения успешна
note left: Соединение не установлено, выход
c --> s: Соединение
note right: Соединение не установлено, выход
==Проверка идентификатора==
c --> s: Отправка идентификатора
hnote across: Сверка идентификатора
s <-- c: Отправка подтверждения
note right: неверный идентификатор, выход
==Идентификация прошла успешно==
@enduml